### ISSUE TITLE
未识别插件

### ISSUE THREAD

**Issue by aurora698** [tumuyan/MusicBeePlug_AlbumCover#1]
您好
我在使用3.3.7491 P版本的musicbee时，按照说明解压插件文件至指定目录后，重启musicbee仍无法识别出插件。
有什么办法进行排查分析吗？

**Comment by tumuyan** [comment]
这不科学...
1. 提供下插件目录文件的截图，我来看下
2. 检查在首选项中是否有xx music artwork名称的插件，是否启用
3. 检查首选项-标签2-封面是否勾选插件

**Comment by udianlaio** [comment]
可以用的  网易跟QQ的都行，就是豆瓣的失效了

**Comment by udianlaio** [comment]
感谢作者的分享
